configfile: "config/config.yaml"


containerized: "docker://alpine:latest"

output_list = ["test2.bam"]

rule all:
    input:
        output_list,


rule bwa:
    output:
        "test2.fastq",
    log:
        "test2.bam",
    conda:
        "envs/env.yaml"
    shell:
        "echo TOTO > {output}"


