# configfile: "config/config.yaml"

output_list = [e.format(i=i) for i in range(10) for e in ["test{i}.sam", "test{i}.fastqc"]]

rule all:
    input:
        output_list,


# rule bwa:
#     output:
#         "test{index}.bam",
#     conda:
#         "envs/env.yaml"
#     container:
#         "docker://biocontainers/bwa:v0.7.17_cv1"
#     shell:
#         """
#         bwa mem > {output}
#         """



rule fastqc:
    output:
        "test{index}.fastqc",
    conda:
        "envs/env.yaml"
    container:
        "docker://biocontainers/fastqc:v0.11.9_cv8"
    shell:
        """
        fastqc --help > {output}
        """




rule samtools:
    output:
        "test{index}.sam",
    conda:
        "envs/env.yaml"
    container:
        "docker://biocontainers/samtools:v1.9-4-deb_cv1"
    shell:
        """
        samtools --help > {output}
        """


