name: Snakemake dev
on:
  push:
    branches:
      - dev

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: snakemake_env
          environment-file: ./env.yaml

      - name: check solution
        run: |
          mamba env export

      - name: test snakemake
        run: |
          which snakemake
          snakemake --version

      - name: Run snakemake
        run: |
          snakemake -c1 --verbose --debug --use-singularity -s ./workflow/Snakefile
