# name: Snakemake dev
# on:
#   push:
#     branches:
#       - dev

# jobs:
#   Create_Dockerfiles:
#     name: Create dockerfiles
#     runs-on: ubuntu-latest
#     steps:

#       - name: Print Dockerfile
#         run: |
#           cat Dockerfile

#       - uses: actions/upload-artifact@master
#         with:
#           name: Dockerfile_artifact
#           path: ./Dockerfile

#   Test_singularity:
#     name: Snakemake x Singularity
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash -l {0}

#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v2

#       - uses: eWaterCycle/setup-singularity@v7
#         with:
#           singularity-version: 3.8.3

#       - name: create environment with mamba
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#           mamba-version: "*"
#           channels: conda-forge,bioconda,defaults
#           auto-activate-base: false
#           activate-environment: snakemake_env
#           environment-file: ./env.yaml

#       - name: check solution
#         run: |
#           mamba env export

#       - name: test snakemake
#         run: |
#           which snakemake
#           snakemake --version

#       - name: Run snakemake
#         run: |
#           snakemake -c1 --verbose --debug --use-singularity -s ./workflow/Snakefile
